wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.21.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1668564192.561813
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      3:
      - 23
      4: 3.9.12
      5: 0.13.5
      6: 4.21.2
      8:
      - 3
      - 5
